import type { Metadata } from "next";
import { CartProvider } from "@/hooks/useCart";

/*export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};*/

export const metadata: Metadata = {
  title: "Smart Apparel Solutions",
  description: "Smart Apparel Solutions",
};

/*export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}*/
export default function RootLayout({
  children,
}: LayoutProps<"/">) {
  return (
    <html lang="en">
      <body>
        <CartProvider>{children}</CartProvider>
      </body>
    </html>
  );
}
